### ISSUE TITLE
surname_year = 2010 throwing error

### ISSUE THREAD

**Issue by lorenc5** [RPVote/eiCompare#72]
Performing BISG to obtain race probabilities.
Error in merge_surnames(voter.file) : object 'surnames2010' not found;

Issue is solved by setting surname_year =2010 instead of assuming the default. Even though this is the default.

**Comment by pssachdeva** [comment]
Looked into this. I'm not sure if it has to do with including the keyword argument (I can't reproduce this error that way). However, I think we will need to switch `wru` to depends, rather than imports. It seems like that's the only way to guarantee we'll have access to the `surnames2010` dataset in `wru`.
